[material]
uri_prefix = "cgi-bin/material"

[media]
uri_prefix = "cgi-bin/media"
with_form_data = true

[menu]
uri_prefix = "cgi-bin/menu"

[card]
uri_prefix = "card"

[card_code]
uri_prefix = "card/code"

[card_user]
uri_prefix = "card/user"

[tags]
uri_prefix = "cgi-bin/tags"

[user]
uri_prefix = "cgi-bin/user"

[template]
uri_prefix = "cgi-bin/template"

[message_template]
uri_prefix = "cgi-bin/message/template"

[message_custom]
uri_prefix = "cgi-bin/message/custom"

[qrcode]
uri_prefix = "cgi-bin/qrcode"

[datacube]
uri_prefix = "datacube"

[poi]
uri_prefix = "cgi-bin/poi"

[showqrcode]
# https://mp.weixin.qq.com/cgi-bin/showqrcode, generate downloadable qrcode.
uri_prefix = "cgi-bin/showqrcode"
host = "https://mp.weixin.qq.com"
http_verbs = ["get"]

[token]
uri_prefix = "cgi-bin/token"
http_verbs = ["get"]
scenario = "hub"
# For component use case, authorizer's access_token is managed by component,
# so generate `token` function is useless in this case.
use_for_component = false

[shorturl]
# https://api.weixin.qq.com/cgi-bin/shorturl, transfer long url into short url
uri_prefix = "cgi-bin/shorturl"
http_verbs = ["post"]

[sns_userinfo]
uri_prefix = "sns/userinfo"

[ticket]
uri_prefix = "cgi-bin/ticket"
http_verbs = ["get"]

